Models/Association.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace ProductsAndCategoriesDec.Models;

public class Association
{

    [Key] // Primary Key
    public int AssociationId { get; set; }

    [Required]
    public int ProductId { get; set; }

    [Required]
    public int CategoryId { get; set; }

    public Product? Product { get; set; }

    public Category? Category { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    public DateTime UpdatedAt { get; set; } = DateTime.Now;
}

Models/Categories.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace ProductsAndCategoriesDec.Models;

public class Categories
{

    [Key] // Primary Key

    public int CategoryId { get; set; }

    [Required (ErrorMessage = "Name is required.")]
    [Display (Name = "Name:")]
    public string Name { get; set; }

    public List<Association> AssociatedProducts { get; set; } = new List<Association>();

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public class Association
    {
        [Key]
        public int AssociationId {get;set;}
        public int ProductId {get;set;}
        public int CategoryId {get;set;}
        public Product Product {get;set;}
        public Categories Category {get;set;}
        public DateTime CreatedAt {get;set;} = DateTime.Now;
        public DateTime UpdatedAt {get;set;} = DateTime.Now;
    }

}

Models/Category.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace ProductsAndCategoriesDec.Models;

public class Category
{

    [Key] // Primary Key

    public int CategoryId { get; set; }

    [Required (ErrorMessage = "Name is required.")]
    [Display (Name = "Name:")]
    public string Name { get; set; }

    public List<Association> AssociatedProducts { get; set; } = new List<Association>();

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;



}

Models/ErrorViewModel.cs
namespace ProductsAndCategoriesDec.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MyContext.cs
#pragma warning disable CS8618

using Microsoft.EntityFrameworkCore;
namespace ProductsAndCategoriesDec.Models;
public class MyContext : DbContext
{
    public MyContext(DbContextOptions options) : base(options) { }

    public DbSet<Category> Categories { get; set; }

    public DbSet<Product> Products { get; set; }

    public DbSet<Association> Associations { get; set; }
}

Models/Product.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace ProductsAndCategoriesDec.Models;

public class Product
{

    [Key]

    public int ProductId { get; set; }

    [Required (ErrorMessage = "Name is required.")]
    [Display (Name = "Name:")]
    public string Name { get; set; }

    [Required (ErrorMessage = "Description is required.")]
    [Display (Name = "Description:")]
    public string Description { get; set; }

    [Required (ErrorMessage = "Price is required.")]
    [DataType (DataType.Currency)]
    [Display (Name = "Price:")]
    public Decimal Price { get; set; }

    public List<Association> AssociatedCategories { get; set; } = new List<Association>();

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;
}

Controllers/CategoriesController.cs
// include this using statement at the top of your controller file
using Microsoft.AspNetCore.Mvc.ModelBinding;



#pragma warning disable CS8618

using Microsoft.AspNetCore.Mvc;
using ProductsAndCategoriesDec.Models;
using Microsoft.EntityFrameworkCore;
namespace ProductsAndCategoriesDec.Controllers;

public class CategoriesController : Controller
{
    private MyContext dbcontext;
    public CategoriesController(MyContext context)
    {
        dbcontext = context;
    }

    [HttpGet("categories")]
    public IActionResult Index()
    {
        List<Category> allCategories = dbcontext.Categories.ToList();
        return View("Index", allCategories);
    }

    [HttpPost("category/new")]
    public IActionResult NewCategory()
    {
        return View("NewCategory");
    }

    [HttpPost("/category/create")]
    public IActionResult create(Category newCategory)
    {
        if (!ModelState.IsValid)
        {
            return NewCategory();
        }
        dbcontext.Categories.Add(newCategory);
        dbcontext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpPost("categories/addproduct")]
    public IActionResult AddProduct(Association association)
    {
        if (ModelState.IsValid)
        {
            dbcontext.Associations.Add(association);
            dbcontext.SaveChanges();
            return OneCategory(association.CategoryId);
        }
        return OneCategory(association.CategoryId);
    }

    [HttpGet("categories/{id}")]
    public IActionResult OneCategory(int id)
    {
        Category? category = dbcontext.Categories
            .Include(p => p.AssociatedProducts)
            .ThenInclude(a => a.Product)
            .FirstOrDefault(c => c.CategoryId == id);

        // this only allows categories to be listed once in the list.
        ViewBag.nonProducts = dbcontext.Products
            .Include(p => p.AssociatedCategories)
            .Where(p => p.AssociatedCategories.All(p => p.CategoryId != id)).OrderBy(p => p.Name).ToList();

        return View("OneCategory", category);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace ProductsAndCategoriesDec.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }


}

Controllers/ProductsController.cs
#pragma warning disable CS8618

using ProductsAndCategoriesDec.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace ProductsAndCategoriesDec.Controllers;

public class ProductsController : Controller
{
    private MyContext dbcontext;
    public ProductsController(MyContext context)
    {
        dbcontext = context;

    }
    [HttpGet("")]
    public IActionResult Index()
    {
        List<Product> allProducts = dbcontext.Products.ToList();
        return View("Index", allProducts);
    }

    [HttpPost("product/new")]
    public IActionResult NewProduct()
    {
        return View("NewProduct");
    }

    [HttpPost("/product/create")]
    public IActionResult Create(Product newProduct)
    {
        if (!ModelState.IsValid)
        {
            return NewProduct();
        }
        dbcontext.Products.Add(newProduct);
        dbcontext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpPost("products/addcategory")]
    public IActionResult AddCategory(Association association)
    {
        if (ModelState.IsValid)
        {
            dbcontext.Associations.Add(association);
            dbcontext.SaveChanges();
            return OneProduct(association.ProductId);
        }
        return OneProduct(association.ProductId);
    }


    [HttpGet("products/{id}")]
    public IActionResult OneProduct(int id)
    {
        Product? product = dbcontext.Products
            .Include(c => c.AssociatedCategories)
            .ThenInclude(a => a.Category)
            .FirstOrDefault(p => p.ProductId == id);

        // this only allows categories to be listed once in the list.
        ViewBag.nonCategories = dbcontext.Categories
            .Include(p => p.AssociatedProducts)
            .Where(p => p.AssociatedProducts.All(p => p.ProductId != id)).OrderBy(p => p.Name).ToList();

        return View("OneProduct", product);
    }
}

Views/Categories/OneCategory.cshtml
@model Category

<div class="text-center">
<h1>@Model.Name</h1>
</div>

<ul>
    @foreach (Association a in Model.AssociatedProducts)
    {
        <li >@a.Product.Name</li>
    }
</ul>

@{
    Association association = new Association();
    association.CategoryId = Model.CategoryId;
}
@await Html.PartialAsync("_AddProducts", association)

Views/Categories/_AddProducts.cshtml
@model Association


<h2>Products!!!</h2>

<form class="d-flex flex-1" asp-action="AddProduct" asp-controller="Categories" method="POST">
    <h3>Add Product</h3>
    <div class="row">
        <input type="hidden" asp-for="CategoryId" value="@Model.CategoryId">
        <select asp-for="ProductId">


            @foreach (var p in ViewBag.nonProducts)
            {
                <option value="@p.ProductId">@p.Name</option>
            }

        </select>
        <span asp-validation-for="CategoryId"></span>
        <span asp-validation-for="ProductId"></span>
    </div>
    <div class="row">
        <input value="Add" type="submit">
    </div>
</form>

Views/Categories/_AllCategories.cshtml
@model List<Category>

<body class="bg-secondary text-light">

@foreach (Category category in Model)
{
    <div>
        <ul>
            <li><a class="text-light" href="/categories/@category.CategoryId">@category.Name</a></li>
        </ul>
    </div>
}
</body>

Views/Categories/_NewCategories.cshtml
@model Category

<body class="bg-secondary text-light">
    <div>
        <form class="Text-center" asp-action="Create" asp-controller="Categories" method="post">
            <div class="text-center mt-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" />
                <span asp-validation-for="Name" class="error"></span>
            </div>
                <input type="submit" value="Enter" class="btn btn-outline-light m-3"></input>
        </form>
    </div>
</body>

Views/Categories/index.cshtml
@model List<Category>

<div class="text-center d-flex justify-content-around">
  <div class="flex-1">
    <h2 class="mt-5 mb-4 text-light">New Category</h2>
    @{
      Category category= new Category();
    }
      @await Html.PartialAsync("_NewCategories", category)
    </div>

    <div class="flex-1">
      <h2 class="mt-5 mb-4 text-light">All Categories</h2>
      @await Html.PartialAsync("_AllCategories", Model)
    </div>
  </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
</div>

Views/Products/Index.cshtml
@model List<Product>

<div class="text-center d-flex justify-content-around">
  <div class="flex-1">
    <h2 class="mt-5 mb-4">New Product</h2>
    @{
      Product product= new Product();
    }
      @await Html.PartialAsync("_NewProduct", product)
    </div>

    <div class="flex-1">
      <h2 class="mt-5 mb-4">All Products</h2>
      @await Html.PartialAsync("_AllProducts", Model)
    </div>
  </div>
</div>

Views/Products/OneProduct.cshtml
@model Product

<div class="text-center">
<h1>@Model.Name</h1>

<ul>
    @foreach (Association a in Model.AssociatedCategories)
    {
        <li>@a.Category.Name</li>
    }
</ul>

@{
    Association association = new Association();
    association.ProductId = Model.ProductId;
}
@await Html.PartialAsync("_AddCategory", association)

Views/Products/_AddCategory.cshtml
@model Association


<form class="" asp-action="AddCategory" asp-controller="Products" method="POST">
    <h3>Add Category:</h3>
    <div class="row">
        <input type="hidden" asp-for="ProductId" value="@Model.ProductId">
        <select asp-for="CategoryId">


            @foreach (var c in ViewBag.nonCategories)
            {
                <option value="@c.CategoryId">@c.Name</option>
            }

        </select>
        <span asp-validation-for="CategoryId"></span>
        <span asp-validation-for="ProductId"></span>
    </div>
    <div class="row">
        <input value="Add" type="submit">
    </div>
</form>

Views/Products/_AllProducts.cshtml
@model List<Product>

<body class="bg-secondary text-light">

@foreach (Product product in Model)
{
    <div>
        <ul>
            <li><a class="text-light" href="/products/@product.ProductId">@product.Name</a></li>
        </ul>
    </div>
}
</body>

Views/Products/_NewProduct.cshtml
@model Product

<body class="bg-secondary text-light">
    <div>
        <form class="Text-center" asp-action="Create" asp-controller="Products" method="post">
            <div class="text-center mt-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" />
                <span asp-validation-for="Name" class="error"></span>
            </div>

            <div class="text-center mt-3">
                <label asp-for="Description"></label>
                <input asp-for="Description" />
                <span asp-validation-for="Description" class="error"></span>
            </div>

            <div class="text-center mt-3">
                <label asp-for="Price"></label>
                <input asp-for="Price" />
                <span asp-validation-for="Price" class="error"></span>
            </div>
                <input type="submit" value="Enter" class="btn btn-outline-light m-3"></input>
        </form>
    </div>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Products and Categories December</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductsAndCategoriesDec.styles.css" asp-append-version="true" />
</head>
<body class="bg-secondary text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="projects" asp-action="Index">Products and Categories December</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        <li class="nav-item">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light">
        <div class="container">
            &copy; 2022 - Products and Categories December</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>